ports:
  - port: 3000
    onOpen: notify
  - port: 3306
    onOpen: ignore

tasks:
  - name: App
    init: |
      pnpm install
    command: |
      echo VITE_DATABASE_URL=mysql://root@127.0.0.1:3306/print-ya > .env
      export VITE_DATABASE_URL=mysql://root@127.0.0.1:3306/print-ya
      pnpm run dev
  - name: Database
    command: |
      brew install planetscale/tap/pscale
      pscale auth login
      pscale org switch print-ya
      pscale connect print-ya develop

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - svelte.svelte-vscode
    - voorjaar.windicss-intellisense
